# Generated by Django 5.2.11 on 2026-02-12 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='walletnonce',
            new_name='accounts_wa_wallet_8a6feb_idx',
            old_name='accounts_wal_wallet_6f17eb_idx',
        ),
    ]
