# Generated by Django 5.2.11 on 2026-02-12 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employer_and_profile_updates'),
        ('accounts', '0002_rename_accounts_wal_wallet_6f17eb_idx_accounts_wa_wallet_8a6feb_idx'),
    ]

    operations = [
    ]
