# Generated by Django 5.2.11 on 2026-02-09 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChainTx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.IntegerField()),
                ('tx_hash', models.CharField(max_length=66, unique=True)),
                ('kind', models.CharField(choices=[('create_payroll', 'create_payroll'), ('fund_vault', 'fund_vault'), ('claim', 'claim'), ('deposit_wrap', 'deposit_wrap'), ('withdraw_unwrap', 'withdraw_unwrap')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('run_id', models.IntegerField(blank=True, null=True)),
                ('payroll_id', models.BigIntegerField(blank=True, null=True)),
                ('employee_wallet', models.CharField(blank=True, default='', max_length=42)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(blank=True, null=True)),
                ('meta', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.organization')),
            ],
        ),
    ]
