# Generated by Django 5.2.11 on 2026-02-12 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('schedule_type', models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('time_of_day', models.TimeField(blank=True, null=True)),
                ('weekday', models.IntegerField(blank=True, null=True)),
                ('day_of_month', models.IntegerField(blank=True, null=True)),
                ('month_of_year', models.IntegerField(blank=True, null=True)),
                ('day_of_year', models.IntegerField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('run_nonce', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_schedules', to='accounts.employer')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_nonce', models.IntegerField(blank=True, null=True)),
                ('payroll_id', models.BigIntegerField(unique=True)),
                ('token', models.CharField(max_length=42)),
                ('vault', models.CharField(max_length=42)),
                ('merkle_root', models.CharField(blank=True, default='', max_length=66)),
                ('total', models.IntegerField(default=0)),
                ('total_amount_units', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('committed', 'Committed'), ('onchain_created', 'Onchain Created'), ('funded', 'Funded'), ('open', 'Open for Claims'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('create_tx_hash', models.CharField(blank=True, default='', max_length=66)),
                ('fund_tx_hash', models.CharField(blank=True, default='', max_length=66)),
                ('claim_window_days', models.IntegerField(default=14)),
                ('close_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='accounts.employer')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='payroll.payrollschedule')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(db_index=True, max_length=42)),
                ('salary_units', models.BigIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='accounts.employer')),
            ],
            options={
                'indexes': [models.Index(fields=['employer', 'active'], name='payroll_emp_employe_217bd0_idx'), models.Index(fields=['employer', 'wallet'], name='payroll_emp_employe_5df4b9_idx')],
                'unique_together': {('employer', 'wallet')},
            },
        ),
        migrations.CreateModel(
            name='PayrollClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_wallet', models.CharField(db_index=True, max_length=42)),
                ('index', models.IntegerField()),
                ('leaf', models.CharField(blank=True, default='', max_length=66)),
                ('proof', models.JSONField(default=list)),
                ('net_ciphertext_b64', models.TextField(blank=True, default='')),
                ('encrypted_ref', models.CharField(blank=True, default='0x0000000000000000000000000000000000000000000000000000000000000000', max_length=66)),
                ('status', models.CharField(choices=[('unclaimed', 'Unclaimed'), ('claimed', 'Claimed')], default='unclaimed', max_length=20)),
                ('claim_tx_hash', models.CharField(blank=True, default='', max_length=66)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='payroll.payrollrun')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'index'], name='payroll_pay_run_id_dbf6dd_idx'), models.Index(fields=['employee_wallet', 'status'], name='payroll_pay_employe_0709fc_idx')],
                'unique_together': {('run', 'employee_wallet')},
            },
        ),
        migrations.AddIndex(
            model_name='payrollschedule',
            index=models.Index(fields=['enabled', 'next_run_at'], name='payroll_pay_enabled_e0a303_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollschedule',
            index=models.Index(fields=['employer', 'enabled'], name='payroll_pay_employe_c8e5b9_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['employer', 'status'], name='payroll_pay_employe_668d66_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['status', 'created_at'], name='payroll_pay_status_97cff9_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['payroll_id'], name='payroll_pay_payroll_556eaf_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(condition=models.Q(('schedule__isnull', False)), fields=('schedule', 'run_nonce'), name='uniq_run_per_schedule_nonce'),
        ),
    ]
