# Generated by Django 5.2.11 on 2026-02-09 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_id', models.BigIntegerField(unique=True)),
                ('token', models.CharField(max_length=42)),
                ('vault', models.CharField(max_length=42)),
                ('merkle_root', models.CharField(blank=True, default='', max_length=66)),
                ('total', models.IntegerField(default=0)),
                ('total_amount_units', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('committed', 'Committed'), ('onchain_created', 'Onchain Created'), ('funded', 'Funded'), ('open', 'Open for Claims'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('create_tx_hash', models.CharField(blank=True, default='', max_length=66)),
                ('fund_tx_hash', models.CharField(blank=True, default='', max_length=66)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(db_index=True, max_length=42)),
                ('salary_units', models.BigIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.organization')),
            ],
            options={
                'unique_together': {('org', 'wallet')},
            },
        ),
        migrations.CreateModel(
            name='PayrollClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_wallet', models.CharField(db_index=True, max_length=42)),
                ('index', models.IntegerField()),
                ('leaf', models.CharField(max_length=66)),
                ('proof', models.JSONField(default=list)),
                ('net_ciphertext_b64', models.TextField()),
                ('encrypted_ref', models.CharField(blank=True, default='0x0000000000000000000000000000000000000000000000000000000000000000', max_length=66)),
                ('status', models.CharField(choices=[('unclaimed', 'Unclaimed'), ('claimed', 'Claimed')], default='unclaimed', max_length=20)),
                ('claim_tx_hash', models.CharField(blank=True, default='', max_length=66)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='payroll.payrollrun')),
            ],
            options={
                'unique_together': {('run', 'employee_wallet')},
            },
        ),
    ]
