# Generated by Django 5.2.11 on 2026-02-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payrollschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='claim_window_days',
            field=models.IntegerField(default=14),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='close_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payrollclaim',
            name='leaf',
            field=models.CharField(blank=True, default='', max_length=66),
        ),
        migrations.AlterField(
            model_name='payrollclaim',
            name='net_ciphertext_b64',
            field=models.TextField(blank=True, default=''),
        ),
    ]
