# Generated by Django 5.2.11 on 2026-02-09 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
        ('payroll', '0003_payrollrun_claim_window_days_payrollrun_close_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollrun',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='payroll.payrollschedule'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='schedule_nonce',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollschedule',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollschedule',
            name='run_nonce',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='orgs.organization'),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_runs', to='orgs.organization'),
        ),
        migrations.AlterField(
            model_name='payrollschedule',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_schedules', to='orgs.organization'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['org', 'active'], name='payroll_emp_org_id_81a075_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['org', 'wallet'], name='payroll_emp_org_id_c81d17_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollclaim',
            index=models.Index(fields=['run', 'index'], name='payroll_pay_run_id_dbf6dd_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollclaim',
            index=models.Index(fields=['employee_wallet', 'status'], name='payroll_pay_employe_0709fc_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['org', 'status'], name='payroll_pay_org_id_6e1646_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['status', 'created_at'], name='payroll_pay_status_97cff9_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollrun',
            index=models.Index(fields=['payroll_id'], name='payroll_pay_payroll_556eaf_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollschedule',
            index=models.Index(fields=['enabled', 'next_run_at'], name='payroll_pay_enabled_e0a303_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollschedule',
            index=models.Index(fields=['org', 'enabled'], name='payroll_pay_org_id_78ab76_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollrun',
            constraint=models.UniqueConstraint(condition=models.Q(('schedule__isnull', False)), fields=('schedule', 'schedule_nonce'), name='uniq_run_per_schedule_nonce'),
        ),
    ]
